export enum PedidoErrorCode {
  MINIMUM_PURCHASE_NOT_REACHED = 'MINIMUM_PURCHASE_NOT_REACHED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  PAYMENT_METHOD_NOT_SUPPORTED = 'PAYMENT_METHOD_NOT_SUPPORTED',
  PEDIDO_NOT_FOUND = 'PEDIDO_NOT_FOUND',
}
